### ISSUE TITLE
Build error (electron-rebuild)

### ISSUE THREAD

**Issue by szekelymilan** [bbondy/bloom-filter-cpp#8]
67b74b483cd17b9dfc90aaf4007b75abb7d31282 causes build errors, `electron-rebuild` cannot run.
[ad-block](https://github.com/brave/ad-block) doesn't run too, because this package is its dependency.
I think you should revert this commit, or fix it. 😃

**Comment by mailtokartik1** [comment]
any updates on this? we need a fix for this.

**Comment by szekelymilan** [comment]
@bbondy Can you do something on this?

**Comment by bbondy** [comment]
Upgrading to node v10 should fix.  Is that possible?

**Comment by bbondy** [comment]
I would accept a patch that fixes it so it can build with both node v10 and prior versions.  Otherwise feel free to fork from an older changeset.

**Comment by szekelymilan** [comment]
node v10 breaks a lot of packages, so most people use node v9, or v8. Upgrading doesn't fix the problem, because other dependencies - of my app - don't work with node v10.
But I'll search for a possible solution. 😃

**Comment by bbondy** [comment]
I'd be happy to implement if you do the work to find a preprocessor directive that can detect between the difference for where this breaks.

**Comment by szekelymilan** [comment]
I am clarifying: electron-rebuild and electron-builder is failing on node-gyp building, but node-gyp alone works like a charm.

**Comment by szekelymilan** [comment]
Solved by forking [@brave/ad-block](https://github.com/brave/ad-block) besides using `npm-shrinkwrap.json`.
